#include "emoji.h"

// Update the emoji list with image file paths
const EmojiEntry emojis[] = {
    {"😃", "grinning face with big eyes"},
    {"😄", "grinning face with smiling eyes"},
    {"😁", "beaming face with smiling eyes"},
    {"😆", "grinning squinting face"},
    {"😅", "grinning face with sweat"},
    {"😂", "face with tears of joy"},
    {"🤣", "rolling on the floor laughing"},
    {"😊", "smiling face with smiling eyes, smile"},
    {"😇", "smiling face with halo"},
    {"🙂", "slightly smiling face"},
    {"🙃", "upside-down face"},
    {"😉", "winking face"},
    {"😌", "relieved face"},
    {"😍", "smiling face with heart-eyes"},
    {"🥰", "smiling face with hearts"},
    {"😘", "face blowing a kiss"},
    {"😗", "kissing face"},
    {"😙", "kissing face with smiling eyes"},
    {"😚", "kissing face with closed eyes"},
    {"😋", "face savoring food"},
    {"😛", "face with tongue"},
    {"😜", "winking face with tongue"},
    {"😝", "squinting face with tongue"},
    {"🤪", "zany face"},
    {"🤨", "face with raised eyebrow"},
    {"🧐", "face with monocle"},
    {"🤓", "nerd face"},
    {"😎", "smiling face with sunglasses"},
    {"🤩", "star-struck face"},
    {"🥳", "partying face"},
    {"😏", "smirking face"},
    {"😒", "unamused face"},
    {"😞", "disappointed face"},
    {"😔", "pensive face"},
    {"😟", "worried face"},
    {"😕", "confused face"},
    {"🙁", "slightly frowning face"},
    {"☹️", "frowning face"},
    {"😣", "persevering face"},
    {"😖", "confounded face"},
    {"😫", "tired face"},
    {"😩", "weary face"},
    {"😤", "face with steam from nose"},
    {"😠", "angry face"},
    {"😡", "pouting face"},
    {"😶‍🌫️", "face in clouds"},
    {"😐", "neutral face"},
    {"😑", "expressionless face"},
    {"😬", "grimacing face"},
    {"🥴", "woozy face"},
    {"😵", "knocked-out face"},
    {"😵‍💫", "face with spiral eyes"},
    {"😲", "astonished face"},
    {"🤯", "exploding head"},
    {"😳", "flushed face"},
    {"🥺", "pleading face"},
    {"😦", "frowning face with open mouth"},
    {"😧", "anguished face"},
    {"😨", "fearful face"},
    {"😰", "anxious face with sweat"},
    {"😱", "face screaming in fear"},
    {"🥵", "hot face"},
    {"🥶", "cold face"},
    {"😳", "flushed face"},
    {"🤗", "hugging face"},
    {"🤔", "thinking face"},
    {"🤭", "face with hand over mouth"},
    {"🤫", "shushing face"},
    {"🤥", "lying face"},
    {"😶", "face without mouth"},
    {"😐", "neutral face"},
    {"😑", "expressionless face"},
    {"😬", "grimacing face"},
    {"🙄", "face with rolling eyes"},
    {"😮‍💨", "face exhaling"},
    {"🤥", "lying face"},
    {"🤫", "shushing face"},
    {"🤔", "thinking face"},
    {"🤨", "face with raised eyebrow"},
    {"😏", "smirking face"},
    {"😣", "persevering face"},
    {"😤", "face with steam from nose"},
    {"😥", "sad but relieved face"},
    {"😦", "frowning face with open mouth"},
    {"😧", "anguished face"},
    {"😨", "fearful face"},
    {"😩", "weary face"},
    {"😪", "sleepy face"},
    {"😫", "tired face"},
    {"😬", "grimacing face"},
    {"😭", "loudly crying face"},
    {"😮", "face with open mouth"},
    {"😯", "hushed face"},
    {"😰", "anxious face with sweat"},
    {"😱", "face screaming in fear"},
    {"😲", "astonished face"},
    {"😳", "flushed face"},
    {"🥺", "pleading face"},
    {"😖", "confounded face"},
    {"😗", "kissing face"},
    {"😙", "kissing face with smiling eyes"},
    {"😚", "kissing face with closed eyes"},
    {"😘", "face blowing a kiss"},
    {"😍", "smiling face with heart-eyes"},
    {"🤩", "star-struck face"},
    {"🤗", "hugging face"},
    {"🤔", "thinking face"},
    {"🤭", "face with hand over mouth"},
    {"🤫", "shushing face"},
    {"🤥", "lying face"},
    {"😶‍🌫️", "face in clouds"},
    {"😐", "neutral face"},
    {"😑", "expressionless face"},
    {"😒", "unamused face"},
    {"🙄", "face with rolling eyes"},
    {"😬", "grimacing face"},
    {"🤥", "lying face"},
    {"🤐", "zipper-mouth face"},
    {"🤨", "face with raised eyebrow"},
    {"😏", "smirking face"},
    {"😣", "persevering face"},
    {"😤", "face with steam from nose"},
    {"😥", "sad but relieved face"},
    {"😦", "frowning face with open mouth"},
    {"😧", "anguished face"},
    {"😨", "fearful face"},
    {"😩", "weary face"},
    {"💀", "skull"},
    {"☠️", "skull and crossbones"},
    {"🪦", "headstone"},
    {"🗿", "moai"},
    {"🐵", "monkey face"},
    {"🐒", "monkey"},
    {"🦍", "gorilla"},
    {"🦧", "orangutan"},
    {"🐶", "dog face"},
    {"🐕", "dog"},
    {"🦮", "guide dog"},
    {"🐕‍🦺", "service dog"},
    {"🐩", "poodle"},
    {"🐺", "wolf"},
    {"🦊", "fox"},
    {"🦝", "raccoon"},
    {"🐱", "cat face"},
    {"🐈", "cat"},
    {"🐈‍⬛", "black cat"},
    {"🦁", "lion"},
    {"🐯", "tiger face"},
    {"🐅", "tiger"},
    {"🐆", "leopard"},
    {"🐴", "horse face"},
    {"🐎", "horse"},
    {"🦄", "unicorn"},
    {"🦓", "zebra"},
    {"🦌", "deer"},
    {"🐮", "cow face"},
    {"🐄", "cow"},
    {"🐂", "ox"},
    {"🐃", "water buffalo"},
    {"🐄", "cow"},
    {"🐖", "pig"},
    {"🐗", "boar"},
    {"🐽", "pig nose"},
    {"🐏", "ram"},
    {"🐑", "ewe"},
    {"🐐", "goat"},
    {"🐪", "camel"},
    {"🐫", "two-hump camel"},
    {"🦙", "llama"},
    {"🦒", "giraffe"},
    {"🐘", "elephant"},
    {"🦣", "mammoth"},
    {"🦏", "rhinoceros"},
    {"🦛", "hippopotamus"},
    {"🐭", "mouse face"},
    {"🐁", "mouse"},
    {"🐀", "rat"},
    {"🐹", "hamster"},
    {"🐰", "rabbit face"},
    {"🐇", "rabbit"},
    {"🐿️", "chipmunk"},
    {"🦫", "beaver"},
    {"🦔", "hedgehog"},
    {"🦇", "bat"},
    {"🐻", "bear"},
    {"🐻‍❄️", "polar bear"},
    {"🐨", "koala"},
    {"🐼", "panda"},
    {"🦥", "sloth"},
    {"🦦", "otter"},
    {"🦨", "skunk"},
    {"🦘", "kangaroo"},
    {"🦡", "badger"},
    {"🐾", "paw prints"},
    {"🦃", "turkey"},
    {"🐔", "chicken"},
    {"🐓", "rooster"},
    {"🐣", "hatching chick"},
    {"🐤", "baby chick"},
    {"🐥", "front-facing baby chick"},
    {"🐦", "bird"},
    {"🐧", "penguin"},
    {"🦅", "eagle"},
    {"🦆", "duck"},
    {"🦢", "swan"},
    {"🦉", "owl"},
    {"🦤", "dodo"},
    {"🪶", "feather"},
    {"🦩", "flamingo"},
    {"🦚", "peacock"},
    {"🦜", "parrot"},
    {"🐸", "frog"},
    {"🐊", "crocodile"},
    {"🐢", "turtle"},
    {"🦎", "lizard"},
    {"🐍", "snake"},
    {"🐲", "dragon face"},
    {"🐉", "dragon"},
    {"🦕", "sauropod"},
    {"🦖", "T-Rex"},
    {"🐳", "spouting whale"},
    {"🐋", "whale"},
    {"🐬", "dolphin"},
    {"🦭", "seal"},
    {"🐟", "fish"},
    {"🐠", "tropical fish"},
    {"🐡", "blowfish"},
    {"🦈", "shark"},
    {"🐙", "octopus"},
    {"🐚", "spiral shell"},
    {"🪸", "coral"},
    {"🐌", "snail"},
    {"🦋", "butterfly"},
    {"🐛", "bug"},
    {"🐜", "ant"},
    {"🐝", "honeybee"},
    {"🪲", "beetle"},
    {"🐞", "lady beetle"},
    {"🦗", "cricket"},
    {"🪳", "cockroach"},
    {"🕷️", "spider"},
    {"🕸️", "spider web"},
    {"🦂", "scorpion"},
    {"🦟", "mosquito"},
    {"🪰", "fly"},
    {"🪱", "worm"},
    {"🍏", "green apple"},
    {"🍎", "red apple"},
    {"🍐", "pear"},
    {"🍊", "tangerine"},
    {"🍋", "lemon"},
    {"🍌", "banana"},
    {"🍉", "watermelon"},
    {"🍇", "grapes"},
    {"🍓", "strawberry"},
    {"🫐", "blueberries"},
    {"🍈", "melon"},
    {"🍒", "cherries"},
    {"🍑", "peach"},
    {"🥭", "mango"},
    {"🍍", "pineapple"},
    {"🥥", "coconut"},
    {"🥝", "kiwi"},
    {"🍅", "tomato"},
    {"🍆", "eggplant"},
    {"🥑", "avocado"},
    {"🥦", "broccoli"},
    {"🥬", "leafy green"},
    {"🥒", "cucumber"},
    {"🌶️", "hot pepper"},
    {"🫑", "bell pepper"},
    {"🌽", "corn"},
    {"🥕", "carrot"},
    {"🫒", "olive"},
    {"🧄", "garlic"},
    {"🧅", "onion"},
    {"🥔", "potato"},
    {"🍠", "roasted sweet potato"},
    {"🥐", "croissant"},
    {"🥯", "bagel"},
    {"🍞", "bread"},
    {"🥖", "baguette bread"},
    {"🫓", "flatbread"},
    {"🥨", "pretzel"},
    {"🥞", "pancakes"},
    {"🧇", "waffle"},
    {"🧀", "cheese wedge"},
    {"🍖", "meat on bone"},
    {"🍗", "poultry leg"},
    {"🥩", "cut of meat"},
    {"🥓", "bacon"},
    {"🍔", "hamburger"},
    {"🍟", "french fries"},
    {"🍕", "pizza"},
    {"🌭", "hot dog"},
    {"🥪", "sandwich"},
    {"🌮", "taco"},
    {"🌯", "burrito"},
    {"🫔", "tamale"},
    {"🥙", "stuffed flatbread"},
    {"🧆", "falafel"},
    {"🥚", "egg"},
    {"🍳", "cooking"},
    {"🥘", "shallow pan of food"},
    {"🍲", "pot of food"},
    {"🫕", "fondue"},
    {"🥣", "bowl with spoon"},
    {"🥗", "green salad"},
    {"🍿", "popcorn"},
    {"🧈", "butter"},
    {"🧂", "salt"},
    {"🥫", "canned food"},
    {"🍱", "bento box"},
    {"🍘", "rice cracker"},
    {"🍙", "rice ball"},
    {"🍚", "cooked rice"},
    {"🍛", "curry rice"},
    {"🍜", "steaming bowl"},
    {"🍝", "spaghetti"},
    {"🍠", "roasted sweet potato"},
    {"🍢", "oden"},
    {"🍣", "sushi"},
    {"🍤", "fried shrimp"},
    {"🍥", "fish cake with swirl"},
    {"🥮", "moon cake"},
    {"🍡", "dango"},
    {"🥟", "dumpling"},
    {"🥠", "fortune cookie"},
    {"🥡", "takeout box"},
    {"🦀", "crab"},
    {"🦞", "lobster"},
    {"🦐", "shrimp"},
    {"🦑", "squid"},
    {"🦪", "oyster"},
    {"🍦", "soft ice cream"},
    {"🍧", "shaved ice"},
    {"🦠", "microbe"},
    {"🌵", "cactus"},
    {"🌲", "evergreen tree"},
    {"🌳", "deciduous tree"},
    {"🌴", "palm tree"},
    {"🌱", "seedling"},
    {"🌿", "herb"},
    {"☘️", "shamrock"},
    {"🍀", "four leaf clover"},
    {"🎄", "Christmas tree"},
    {"🌍", "globe showing Europe-Africa"},
    {"🌎", "globe showing Americas"},
    {"🌏", "globe showing Asia-Australia"},
    {"🌐", "globe with meridians"},
    {"🌋", "volcano"},
    {"🗻", "mount fuji"},
    {"🏔️", "snow-capped mountain"},
    {"⛰️", "mountain"},
    {"🌠", "shooting star"},
    {"🌌", "milky way"},
    {"🎇", "sparkler"},
    {"🎆", "fireworks"},
    {"🌈", "rainbow"},
    {"🏝️", "desert island"},
    {"🏜️", "desert"},
    {"🏞️", "national park"},
    {"🏟️", "stadium"},
    {"🏛️", "classical building"},
    {"🏗️", "building construction"},
    {"🧱", "brick"},
    {"🏘️", "houses"},
    {"🏚️", "derelict house"},
    {"🏠", "house"},
    {"🏡", "house with garden"},
    {"🏢", "office building"},
    {"🏣", "Japanese post office"},
    {"🏤", "post office"},
    {"🏥", "hospital"},
    {"🏦", "bank"},
    {"🏨", "hotel"},
    {"🏩", "love hotel"},
    {"🏪", "convenience store"},
    {"🏫", "school"},
    {"🏬", "department store"},
    {"🏭", "factory"},
    {"🏰", "castle"},
    {"💒", "wedding"},
    {"🗼", "Tokyo tower"},
    {"🗽", "Statue of Liberty"},
    {"⛪", "church"},
    {"🕌", "mosque"},
    {"🛕", "hindu temple"},
    {"🕍", "synagogue"},
    {"⛩️", "shinto shrine"},
    {"🕋", "kaaba"},
    {"⛲", "fountain"},
    {"🛢️", "oil drum"},
    {"🛣️", "motorway"},
    {"🗾", "map of Japan"},
    {"🗿", "moai"},
    {"🛤️", "railway track"},
    {"🛳️", "passenger ship"},
    {"🛥️", "motor boat"},
    {"🚢", "ship"},
    {"✈️", "airplane"},
    {"🛩️", "small airplane"},
    {"🛫", "airplane departure"},
    {"🛬", "airplane arrival"},
    {"💺", "seat"},
    {"🚁", "helicopter"},
    {"🚟", "suspension railway"},
    {"🚠", "mountain cableway"},
    {"🚡", "aerial tramway"},
    {"🚀", "rocket"},
    {"🛸", "flying saucer"},
    {"🛰️", "satellite"},
    {"🌠", "shooting star"},
    {"🌌", "milky way"},
    {"🎇", "sparkler"},
    {"🎆", "fireworks"},
    {"🌈", "rainbow"},
    {"🏝️", "desert island"},
    {"🏜️", "desert"},
    {"🏞️", "national park"},
    {"🏟️", "stadium"},
    {"🏛️", "classical building"},
    {"🏗️", "building construction"},
    {"🧱", "brick"},
    {"🏘️", "houses"},
    {"🏚️", "derelict house"},
    {"🏠", "house"},
    {"🏡", "house with garden"},
    {"🏢", "office building"},
    {"🏣", "Japanese post office"},
    {"🏤", "post office"},
    {"🏥", "hospital"},
    {"🏦", "bank"},
    {"🏨", "hotel"},
    {"🏩", "love hotel"},
    {"🏪", "convenience store"},
    {"🏫", "school"},
    {"🏬", "department store"},
    {"🏭", "factory"},
    {"🏰", "castle"},
    {"💒", "wedding"},
    {"🗼", "Tokyo tower"},
    {"🗽", "Statue of Liberty"},
    {"⛪", "church"},
    {"🕌", "mosque"},
    {"🛕", "hindu temple"},
    {"🕍", "synagogue"},
    {"⛩️", "shinto shrine"},
    {"🕋", "kaaba"},
    {"⛲", "fountain"},
    {"🛢️", "oil drum"},
    {"🛣️", "motorway"},
    {"🗾", "map of Japan"},
    {"🗿", "moai"},
    {"🛤️", "railway track"},
    {"🛳️", "passenger ship"},
    {"🛥️", "motor boat"},
    {"🚢", "ship"},
    {"✈️", "airplane"}
};

// Definition of the NUM_EMOJIS variable
const size_t NUM_EMOJIS = sizeof(emojis) / sizeof(emojis[0]);