#include "emoji.h"

// Update the emoji list with image file paths
const EmojiEntry emojis[] = {
    {"😛", "face with tongue playfulness"},
    {"😜", "winking face with tongue playfulness"},
    {"😝", "squinting face with tongue playfulness"},
    {"🤪", "zany face crazy"},
    {"🤨", "face with raised eyebrow curiosity"},
    {"🧐", "face with monocle curiosity"},
    {"🤓", "nerd face intelligence glasses"},
    {"😎", "smiling face with sunglasses cool smile"},
    {"🤩", "star-struck face amazement"},
    {"😏", "smirking face satisfaction"},
    {"😒", "unamused face disapproval"},
    {"😞", "disappointed face sadness"},
    {"😔", "pensive face concern"},
    {"😟", "worried face concern"},
    {"😕", "confused face confusion"},
    {"🙁", "slightly frowning face sadness"},
    {"☹️", "frowning face sadness"},
    {"😣", "persevering face determination"},
    {"😖", "confounded face frustration"},
    {"😫", "tired face exhaustion"},
    {"😩", "weary face exhaustion"},
    {"😤", "face with steam from nose frustration"},
    {"😠", "angry face anger"},
    {"😡", "pouting face anger"},
    {"😶‍🌫️", "face in clouds silent"},
    {"😐", "neutral face neutrality"},
    {"😑", "expressionless face blankness"},
    {"😬", "grimacing face discomfort"},
    {"🥲", "smiling face with tear"},
    {"😳", "flushed face embarrassment"},
    {"🥺", "pleading face"},
    {"😦", "frowning face with open mouth surprise"},
    {"😧", "anguished face distress"},
    {"😨", "fearful face fear"},
    {"😰", "anxious face with sweat fear"},
    {"😱", "face screaming in fear horror"},
    {"😵", "knocked-out face unconsciousness"},
    {"😲", "astonished face amazement"},
    {"😷", "face with medical mask health"},
    {"🤒", "face with thermometer sickness"},
    {"🤕", "face with head-bandage injury"},
    {"🤢", "nauseated face sickness"},
    {"🤮", "face vomiting sickness"},
    {"🤧", "sneezing face sickness"},
    {"😇", "smiling face with halo angel"},
    {"🥰", "smiling face with hearts affection"},
    {"🤩", "star-struck face amazement"},
    {"🤯", "exploding head shock"},
    {"🤪", "zany face crazy"},
    {"🤭", "face with hand over mouth playful"},
    {"🧐", "face with monocle curiosity"},
    {"🤫", "shushing face silence"},
    {"🤥", "lying face dishonesty"},
    {"😶‍🌫️", "face in clouds silent"},
    {"🤐", "zipper-mouth face secrecy"},
    {"🤨", "face with raised eyebrow curiosity"},
    {"😏", "smirking face satisfaction"},
    {"😒", "unamused face disapproval"},
    {"🙄", "face with rolling eyes annoyance"},
    {"😬", "grimacing face discomfort"},
    {"😮‍💨", "face exhaling steam"},
    {"🤥", "lying face dishonesty"},
    {"🤫", "shushing face silence"},
    {"🤔", "thinking face"},
    {"🤨", "face with raised eyebrow"},
    {"😏", "smirking face"},
    {"😣", "persevering face"},
    {"😤", "face with steam from nose"},
    {"😥", "sad but relieved face"},
    {"😦", "frowning face with open mouth"},
    {"😧", "anguished face"},
    {"😨", "fearful face"},
    {"😩", "weary face"},
    {"😪", "sleepy face"},
    {"😫", "tired face"},
    {"😬", "grimacing face"},
    {"😭", "loudly crying face"},
    {"😮", "face with open mouth"},
    {"😯", "hushed face"},
    {"😰", "anxious face with sweat"},
    {"😱", "face screaming in fear"},
    {"😲", "astonished face"},
    {"😳", "flushed face"},
    {"🥺", "pleading face"},
    {"😦", "frowning face with open mouth"},
    {"😧", "anguished face"},
    {"😨", "fearful face"},
    {"😩", "weary face"},
    {"😪", "sleepy face"},
    {"😫", "tired face"},
    {"😬", "grimacing face"},
    {"😭", "loudly crying face"},
    {"😮", "face with open mouth"},
    {"😯", "hushed face"},
    {"😰", "anxious face with sweat"},
    {"😱", "face screaming in fear"},
    {"😲", "astonished face"},
    {"😳", "flushed face"},
    {"🥺", "pleading face"},
    {"😖", "confounded face"},
    {"😗", "kissing face"},
    {"😙", "kissing face with smiling eyes"},
    {"😚", "kissing face with closed eyes"},
    {"😘", "face blowing a kiss"},
    {"😍", "smiling face with heart-eyes"},
    {"🤩", "star-struck face"},
    {"🤗", "hugging face"},
    {"🤔", "thinking face"},
    {"🤭", "face with hand over mouth"},
    {"🤫", "shushing face"},
    {"🤥", "lying face"},
    {"😶‍🌫️", "face in clouds"},
    {"😐", "neutral face"},
    {"😑", "expressionless face"},
    {"😒", "unamused face"},
    {"🙄", "face with rolling eyes"},
    {"😬", "grimacing face"},
    {"🤥", "lying face"},
    {"🤐", "zipper-mouth face"},
    {"🤨", "face with raised eyebrow"},
    {"😏", "smirking face"},
    {"😣", "persevering face"},
    {"😤", "face with steam from nose"},
    {"😥", "sad but relieved face"},
    {"😦", "frowning face with open mouth"},
    {"😧", "anguished face"},
    {"😨", "fearful face"},
    {"😩", "weary face"},
    {"🐶", "dog"},
    {"🐱", "cat"},
    {"🐭", "mouse"},
    {"🐹", "hamster"},
    {"🐰", "rabbit"},
    {"🦊", "fox"},
    {"🐻", "bear"},
    {"🐼", "panda"},
    {"🐨", "koala"},
    {"🐯", "tiger"},
    {"🦁", "lion"},
    {"🐮", "cow"},
    {"🐷", "pig"},
    {"🐸", "frog"},
    {"🐵", "monkey"},
    {"🐔", "chicken"},
    {"🐧", "penguin"},
    {"🐦", "bird"},
    {"🐤", "baby chick"},
    {"🐣", "hatching chick"},
    {"🐥", "front-facing baby chick"},
    {"🦆", "duck"},
    {"🦅", "eagle"},
    {"🦉", "owl"},
    {"🦇", "bat"},
    {"🐺", "wolf"},
    {"🐗", "boar"},
    {"🐴", "horse"},
    {"🦄", "unicorn"},
    {"🐝", "honeybee"},
    {"🐛", "bug"},
    {"🦋", "butterfly"},
    {"🐌", "snail"},
    {"🐞", "lady beetle"},
    {"🐜", "ant"},
    {"🦗", "cricket"},
    {"🕷️", "spider"},
    {"🦂", "scorpion"},
    {"🦟", "mosquito"},
    {"🦠", "microbe"},
    {"🌵", "cactus"},
    {"🌲", "evergreen tree"},
    {"🌳", "deciduous tree"},
    {"🌴", "palm tree"},
    {"🌱", "seedling"},
    {"🌿", "herb"},
    {"☘️", "shamrock"},
    {"🍀", "four leaf clover"},
    {"🎄", "Christmas tree"},
    {"🌍", "globe showing Europe-Africa"},
    {"🌎", "globe showing Americas"},
    {"🌏", "globe showing Asia-Australia"},
    {"🌐", "globe with meridians"},
    {"🌋", "volcano"},
    {"🗻", "mount fuji"},
    {"🏔️", "snow-capped mountain"},
    {"⛰️", "mountain"},
    {"🌠", "shooting star"},
    {"🌌", "milky way"},
    {"🎇", "sparkler"},
    {"🎆", "fireworks"},
    {"🌈", "rainbow"},
    {"🏝️", "desert island"},
    {"🏜️", "desert"},
    {"🏞️", "national park"},
    {"🏟️", "stadium"},
    {"🏛️", "classical building"},
    {"🏗️", "building construction"},
    {"🧱", "brick"},
    {"🏘️", "houses"},
    {"🏚️", "derelict house"},
    {"🏠", "house"},
    {"🏡", "house with garden"},
    {"🏢", "office building"},
    {"🏣", "Japanese post office"},
    {"🏤", "post office"},
    {"🏥", "hospital"},
    {"🏦", "bank"},
    {"🏨", "hotel"},
    {"🏩", "love hotel"},
    {"🏪", "convenience store"},
    {"🏫", "school"},
    {"🏬", "department store"},
    {"🏭", "factory"},
    {"🏰", "castle"},
    {"💒", "wedding"},
    {"🗼", "Tokyo tower"},
    {"🗽", "Statue of Liberty"},
    {"⛪", "church"},
    {"🕌", "mosque"},
    {"🛕", "hindu temple"},
    {"🕍", "synagogue"},
    {"⛩️", "shinto shrine"},
    {"🕋", "kaaba"},
    {"⛲", "fountain"},
    {"🛢️", "oil drum"},
    {"🛣️", "motorway"},
    {"🗾", "map of Japan"},
    {"🗿", "moai"},
    {"🛤️", "railway track"},
    {"🛳️", "passenger ship"},
    {"🛥️", "motor boat"},
    {"🚢", "ship"},
    {"✈️", "airplane"},
    {"🛩️", "small airplane"},
    {"🛫", "airplane departure"},
    {"🛬", "airplane arrival"},
    {"💺", "seat"},
    {"🚁", "helicopter"},
    {"🚟", "suspension railway"},
    {"🚠", "mountain cableway"},
    {"🚡", "aerial tramway"},
    {"🚀", "rocket"},
    {"🛸", "flying saucer"},
    {"🛰️", "satellite"},
    {"🌠", "shooting star"},
    {"🌌", "milky way"},
    {"🎇", "sparkler"},
    {"🎆", "fireworks"},
    {"🌈", "rainbow"},
    {"🏝️", "desert island"},
    {"🏜️", "desert"},
    {"🏞️", "national park"},
    {"🏟️", "stadium"},
    {"🏛️", "classical building"},
    {"🏗️", "building construction"},
    {"🧱", "brick"},
    {"🏘️", "houses"},
    {"🏚️", "derelict house"},
    {"🏠", "house"},
    {"🏡", "house with garden"},
    {"🏢", "office building"},
    {"🏣", "Japanese post office"},
    {"🏤", "post office"},
    {"🏥", "hospital"},
    {"🏦", "bank"},
    {"🏨", "hotel"},
    {"🏩", "love hotel"},
    {"🏪", "convenience store"},
    {"🏫", "school"},
    {"🏬", "department store"},
    {"🏭", "factory"},
    {"🏰", "castle"},
    {"💒", "wedding"},
    {"🗼", "Tokyo tower"},
    {"🗽", "Statue of Liberty"},
    {"⛪", "church"},
    {"🕌", "mosque"},
    {"🛕", "hindu temple"},
    {"🕍", "synagogue"},
    {"⛩️", "shinto shrine"},
    {"🕋", "kaaba"},
    {"⛲", "fountain"},
    {"🛢️", "oil drum"},
    {"🛣️", "motorway"},
    {"🗾", "map of Japan"},
    {"🗿", "moai"},
    {"🛤️", "railway track"},
    {"🛳️", "passenger ship"},
    {"🛥️", "motor boat"},
    {"🚢", "ship"},
    {"✈️", "airplane"}
};

// Definition of the NUM_EMOJIS variable
const size_t NUM_EMOJIS = sizeof(emojis) / sizeof(emojis[0]);